### ISSUE TITLE
Person and Literature

### ISSUE THREAD

**Issue by Wieps** [martijnbentum/istanbul#1]
'Event' moet aan 'Person' én/of 'Literature' gehangen woerden. Met invoeren werken we vanuit 'Event' waar je meerdere records 'Literature' and 'Persons' aan wilt hangen. Zoals het nu is, voelt het omgekeerd en je moet het via een omweg doen. Je bent met een 'Event' bezig. Dat sla je op en dan moet je langs de personen en de literatuur om dat 'Event' te koppelen

**Comment by martijnbentum** [comment]
Ik snap de vraag niet helemaal. Je kan nu op beide manieren koppelen. Vanuit event -> person en literature. En vanuit person, literature -> event koppelen. Wat ontbreekt er?

**Comment by Wieps** [comment]
Ja dat zie ik nu ook. Wij zullen iets niet goed gedaan hebben want wij voerden een installation in en vanuit daar meteen een event. Toen verschenen daar geen persons of literature. Of ij hebben niet goed gekeken. Maar dit punt is dus al opgelost.

Met vriendelijke groet,

Willy

drs. Willy Piron | Hoofd Centrum voor Kunsthistorische Documentatie
Radboud Universiteit Nijmegen | Afdeling Kunstgeschiedenis
Postbus 9103, 6500 HD, Nijmegen | Bezoekadres: Erasmusplein 1, Kamer 11.14, 6525 HT Nijmegen
Tel: 024-3612623

Van: martijnbentum ***@***.***>
Verzonden: vrijdag 26 augustus 2022 14:49
Aan: martijnbentum/istanbul ***@***.***>
CC: Piron, H.W.J. (Willy) ***@***.***>; Author ***@***.***>
Onderwerp: Re: [martijnbentum/istanbul] Person and Literature (Issue #1)


Ik snap de vraag niet helemaal. Je kan nu op beide manieren koppelen. Vanuit event -> person en literature. En vanuit person, literature -> event koppelen. Wat ontbreekt er?

**Comment by martijnbentum** [comment]
mooi dan sluit ik het issue
