### ISSUE TITLE
'Save' bij Literatuur description werkt niet

### ISSUE THREAD

**Issue by marietteverhoeven** [martijnbentum/istanbul#11]
Hoi Martijn,

Ik moet je toch nog even lastig vallen met een issue. De studentassistente voert momenteel Literatuur in en als ze dan tekst bij 'Description' invoert en op save klikt wordt de tekst niet opgeslagen en verdwijnt. Zou jij kunnen checken wat hier aan de hand is?

Hartelijke groet,
Mariëtte

**Comment by martijnbentum** [comment]
Geen probleem als het goed is, is het nu opgelost.
