### ISSUE TITLE
Save knop

### ISSUE THREAD

**Issue by Wieps** [martijnbentum/istanbul#4]
De Save knop onderaan de Add-formulieren is onduidelijk. Bijvoorbeeld bij Add Event; save je dan het 'Event' of save je de literatuur die je eraan toevoegt? Watn er staat ook nog een knop naast die heet 'save / add another'.

**Comment by martijnbentum** [comment]
ik denk dat we dit het makkelijkste kunnen oplossen als we even overleggen (bijv. via zoom )

**Comment by Wieps** [comment]
Dit is niet cruciaal. Misschien is het handiger als Mariëtte eerst nog wat invoert om het systeem te testen en dat we dan een keer een zoom-afspraak maken
