### ISSUE TITLE
Detailscherm

### ISSUE THREAD

**Issue by Wieps** [martijnbentum/istanbul#9]
We willen graag een detailpagina voor ‘Installaties’

Die zou het volgende moeten bevatten:

Uit de tabel ‘Istallatie’ de velden ‘Engelse naam’ en ‘originele naam’,  en ‘still exists’

Uit de tabel ‘Events’ de velden ‘name’ en ‘start date’ en ‘end date’ 

Uit de tabel ‘Person’ de velden ‘name’ en ‘role’

**Comment by martijnbentum** [comment]
Ik heb een link toegevoegd boven aan de add installation pagina. Als je op het oogje klikt ga je naar de detail pagina
